/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ThemeType } from "./types";
import { SpaceSize } from "./components/space/index";
export { ThemeType } from "./types";
export { SpaceSize } from "./components/space/index";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WcButton {
        /**
          * 按钮是否为块级元素，默认为 `false`
         */
        "block": boolean;
        /**
          * 是否为暗黑模式，默认为 `false`
         */
        "dark": boolean;
        /**
          * 按钮是否禁用，默认为 `false`
         */
        "disabled": boolean;
        /**
          * 主题色阶号，可选值为 `1` `2` `3` `4` `5` `6` `7` `8` `9` `10`
         */
        "level": number;
        /**
          * 按钮是否加载中，默认为 `false`
         */
        "loading": boolean;
        /**
          * 矩形圆角大小，单位为 `px`，默认为 `4px`
         */
        "radius": number;
        /**
          * 按钮形状，可选值为 `rectangle` `square` `round` `circle`，默认为 `rectangle`
         */
        "shape": 'rectangle' | 'square' | 'round' | 'circle';
        /**
          * 按钮尺寸，可选值为 `mini` `small` `medium` `large` 或者具体的数值，默认为 `medium`
         */
        "size": 'mini' | 'small' | 'medium' | 'large' | number;
        /**
          * 按钮文本，也可通过默认插槽设置文本
         */
        "text": string;
        /**
          * 按钮风格，可选值为 `default` `primary` `success` `warning` `danger`，默认为 `default`
         */
        "theme": ThemeType;
        /**
          * 按钮类型，可选值为 `submit` `reset` `button`，默认为 `button`
         */
        "type": 'submit' | 'reset' | 'button';
        /**
          * 按钮变体，可选值为 `base` `outline` `dashed` `text` `contained`，默认为 `base`
         */
        "variant": 'base' | 'outline' | 'dashed' | 'text' | 'contained';
        /**
          * 按钮是否可见，默认为 `true`
         */
        "visible": boolean;
    }
    interface WcButtonGroup {
    }
    interface WcIcon {
        /**
          * 自定义类名
         */
        "customClass": string;
        /**
          * 自定义样式
         */
        "customStyle": string | object;
        /**
          * 是否旋转
         */
        "spin": boolean;
        /**
          * 图标类型
         */
        "type": string;
    }
    interface WcSpace {
        /**
          * 对齐方式，可选值为 `start` `end` `center` `baseline` `stretch`，默认为 `start`
         */
        "align": 'start' | 'end' | 'center' | 'baseline' | 'stretch';
        /**
          * 子元素是否为块级元素
         */
        "block": boolean;
        /**
          * 节点类名
         */
        "customClass": string | string[];
        /**
          * 节点样式
         */
        "customStyle": {
        [key: string]: string
    } | string;
        /**
          * 间距方向，可选值为 `horizontal` `vertical`，默认为 `horizontal`
         */
        "direction": 'horizontal' | 'vertical';
        /**
          * 间距大小，可选值为 `mini` `small` `medium` `large` 或者具体的数值，默认为 `small`
         */
        "size": SpaceSize | SpaceSize[];
        /**
          * 是否为环绕排列，默认为 `false`
         */
        "wrap": boolean;
    }
    interface WcSpaceItem {
    }
}
export interface WcButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLWcButtonElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWcButtonElement extends Components.WcButton, HTMLStencilElement {
    }
    var HTMLWcButtonElement: {
        prototype: HTMLWcButtonElement;
        new (): HTMLWcButtonElement;
    };
    interface HTMLWcButtonGroupElement extends Components.WcButtonGroup, HTMLStencilElement {
    }
    var HTMLWcButtonGroupElement: {
        prototype: HTMLWcButtonGroupElement;
        new (): HTMLWcButtonGroupElement;
    };
    interface HTMLWcIconElement extends Components.WcIcon, HTMLStencilElement {
    }
    var HTMLWcIconElement: {
        prototype: HTMLWcIconElement;
        new (): HTMLWcIconElement;
    };
    interface HTMLWcSpaceElement extends Components.WcSpace, HTMLStencilElement {
    }
    var HTMLWcSpaceElement: {
        prototype: HTMLWcSpaceElement;
        new (): HTMLWcSpaceElement;
    };
    interface HTMLWcSpaceItemElement extends Components.WcSpaceItem, HTMLStencilElement {
    }
    var HTMLWcSpaceItemElement: {
        prototype: HTMLWcSpaceItemElement;
        new (): HTMLWcSpaceItemElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "wc-button": HTMLWcButtonElement;
        "wc-button-group": HTMLWcButtonGroupElement;
        "wc-icon": HTMLWcIconElement;
        "wc-space": HTMLWcSpaceElement;
        "wc-space-item": HTMLWcSpaceItemElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WcButton {
        /**
          * 按钮是否为块级元素，默认为 `false`
         */
        "block"?: boolean;
        /**
          * 是否为暗黑模式，默认为 `false`
         */
        "dark"?: boolean;
        /**
          * 按钮是否禁用，默认为 `false`
         */
        "disabled"?: boolean;
        /**
          * 主题色阶号，可选值为 `1` `2` `3` `4` `5` `6` `7` `8` `9` `10`
         */
        "level"?: number;
        /**
          * 按钮是否加载中，默认为 `false`
         */
        "loading"?: boolean;
        /**
          * 点击事件
         */
        "onClick"?: (event: WcButtonCustomEvent<MouseEvent>) => void;
        /**
          * 矩形圆角大小，单位为 `px`，默认为 `4px`
         */
        "radius"?: number;
        /**
          * 按钮形状，可选值为 `rectangle` `square` `round` `circle`，默认为 `rectangle`
         */
        "shape"?: 'rectangle' | 'square' | 'round' | 'circle';
        /**
          * 按钮尺寸，可选值为 `mini` `small` `medium` `large` 或者具体的数值，默认为 `medium`
         */
        "size"?: 'mini' | 'small' | 'medium' | 'large' | number;
        /**
          * 按钮文本，也可通过默认插槽设置文本
         */
        "text"?: string;
        /**
          * 按钮风格，可选值为 `default` `primary` `success` `warning` `danger`，默认为 `default`
         */
        "theme"?: ThemeType;
        /**
          * 按钮类型，可选值为 `submit` `reset` `button`，默认为 `button`
         */
        "type"?: 'submit' | 'reset' | 'button';
        /**
          * 按钮变体，可选值为 `base` `outline` `dashed` `text` `contained`，默认为 `base`
         */
        "variant"?: 'base' | 'outline' | 'dashed' | 'text' | 'contained';
        /**
          * 按钮是否可见，默认为 `true`
         */
        "visible"?: boolean;
    }
    interface WcButtonGroup {
    }
    interface WcIcon {
        /**
          * 自定义类名
         */
        "customClass"?: string;
        /**
          * 自定义样式
         */
        "customStyle"?: string | object;
        /**
          * 是否旋转
         */
        "spin"?: boolean;
        /**
          * 图标类型
         */
        "type"?: string;
    }
    interface WcSpace {
        /**
          * 对齐方式，可选值为 `start` `end` `center` `baseline` `stretch`，默认为 `start`
         */
        "align"?: 'start' | 'end' | 'center' | 'baseline' | 'stretch';
        /**
          * 子元素是否为块级元素
         */
        "block"?: boolean;
        /**
          * 节点类名
         */
        "customClass"?: string | string[];
        /**
          * 节点样式
         */
        "customStyle"?: {
        [key: string]: string
    } | string;
        /**
          * 间距方向，可选值为 `horizontal` `vertical`，默认为 `horizontal`
         */
        "direction"?: 'horizontal' | 'vertical';
        /**
          * 间距大小，可选值为 `mini` `small` `medium` `large` 或者具体的数值，默认为 `small`
         */
        "size"?: SpaceSize | SpaceSize[];
        /**
          * 是否为环绕排列，默认为 `false`
         */
        "wrap"?: boolean;
    }
    interface WcSpaceItem {
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "wc-button": WcButton;
        "wc-button-group": WcButtonGroup;
        "wc-icon": WcIcon;
        "wc-space": WcSpace;
        "wc-space-item": WcSpaceItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "wc-button": LocalJSX.WcButton & JSXBase.HTMLAttributes<HTMLWcButtonElement>;
            "wc-button-group": LocalJSX.WcButtonGroup & JSXBase.HTMLAttributes<HTMLWcButtonGroupElement>;
            "wc-icon": LocalJSX.WcIcon & JSXBase.HTMLAttributes<HTMLWcIconElement>;
            "wc-space": LocalJSX.WcSpace & JSXBase.HTMLAttributes<HTMLWcSpaceElement>;
            "wc-space-item": LocalJSX.WcSpaceItem & JSXBase.HTMLAttributes<HTMLWcSpaceItemElement>;
        }
    }
}
